name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '17'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Konan
        id: cache-konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan
      - name: Cache Gradle Caches
        uses: gradle/actions/setup-gradle@v4
      - name: Run Gradle tasks
        run: ./gradlew check
      - name: Publish Test Report
        uses: test-summary/action@v2
        if: ${{ !cancelled() }}
        with:
          paths: '**/build/test-results/**/TEST-*.xml'
